# ==========================================
# Level 2: Target Nodes
# ==========================================

[databases]
db ansible_host=192.168.56.10 ansible_ssh_private_key_file=.vagrant/machines/db/libvirt/private_key

[caches]
cache ansible_host=192.168.56.11 ansible_ssh_private_key_file=.vagrant/machines/cache/libvirt/private_key

[webservers]
web ansible_host=192.168.56.12 ansible_ssh_private_key_file=.vagrant/machines/web/libvirt/private_key

# ==========================================
# Global Variables for all machines
# ==========================================
[all:vars]
ansible_user=vagrant
ansible_become=yes
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3