Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  
  # Ensure we are using the libvirt provider
  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 1024 # We can use less RAM per machine since they are split up!
    libvirt.cpus = 1
  end

  # ==========================================
  # Node 1: The Database Server (PostgreSQL)
  # ==========================================
  config.vm.define "db" do |db|
    db.vm.hostname = "db-server"
    db.vm.network "private_network", ip: "192.168.56.10"
  end

  # ==========================================
  # Node 2: The Cache Server (Redis)
  # ==========================================
  config.vm.define "cache" do |cache|
    cache.vm.hostname = "cache-server"
    cache.vm.network "private_network", ip: "192.168.56.11"
  end

  # ==========================================
  # Node 3: The Web Server (Node.js + Nginx)
  # ==========================================
  config.vm.define "web" do |web|
    web.vm.hostname = "web-server"
    web.vm.network "private_network", ip: "192.168.56.12"
    
    web.vm.synced_folder "../dummy-node-app", "/vagrant/dummy-node-app", type: "rsync"
  end
end