# inventory.ini

[web]
98.91.186.198

[db]
10.0.2.197

[cache]
10.0.2.8

[all:vars]
# Point directly to the absolute path of the key
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/ansuman/Documents/Tech/Creds/aws-project-key.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[db:vars]
# Removed the leading dot from the -i path
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ubuntu@98.91.186.198 -i /home/ansuman/Documents/Tech/Creds/aws-project-key.pem -o StrictHostKeyChecking=no"'

[cache:vars]
# Removed the leading dot from the -i path
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ubuntu@98.91.186.198 -i /home/ansuman/Documents/Tech/Creds/aws-project-key.pem -o StrictHostKeyChecking=no"'