Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  
  # 1. Sync the current directory (so bootstrap.sh gets copied to /vagrant)
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  
  # 2. Reach up to the parent directory to grab the app, and place it exactly 
  # where the Bash script expects it to be (/vagrant/dummy-node-app)
  config.vm.synced_folder "../dummy-node-app", "/vagrant/dummy-node-app", type: "rsync"
  
  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 2048
    libvirt.cpus = 2
  end
end