Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  
  # Explicitly tell libvirt to sync the current directory to /vagrant using rsync
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  
  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 2048
    libvirt.cpus = 2
  end
end